#!/bin/sh

echo Creating output directory
rm -r output
mkdir output

echo Compiling main HTML file
node -e "$(cat <<END_NODE
  file = require('fs').readFileSync('client/index.html.ejs', 'utf8');
  index = require('ejs').render(file, { environment: 'build' })
         .replace(/<script[^>]+>/, '<script src="scripts/main.js">')
         .replace('stylesheets/main', 'stylesheets/main.css')
  console.log(index);
END_NODE
)" > output/index_full.html
if which html5small > /dev/null 2>&1; then
  echo Compressing main HTML file
  html5small output/index_full.html > output/index.html
  rm output/index_full.html
else
  mv output/index_full.html output/index.html
fi

echo Compiling stylesheet
mkdir output/stylesheets
node_modules/less/bin/lessc --compress client/stylesheets/main.less > output/stylesheets/main_full.css
if which csspress > /dev/null 2>&1; then
  echo Compressing stylesheet
  csspress output/stylesheets/main_full.css > output/stylesheets/main.css
  rm output/stylesheets/main_full.css
else
  mv output/stylesheets/main_full.css output/stylesheets/main.css
fi

echo Copying fonts
cp client/stylesheets/*.otf client/stylesheets/*.ttf output/stylesheets

echo Copying image files
cp -r client/images output

echo Copying swf files
cp client/stylesheets/*.swf output/scripts/swf

echo Compiling JavaScript files
cd client/scripts
../../node_modules/requirejs/bin/r.js -o app.build.js
cd ../..
mkdir output/scripts
mv client/scripts/main-built.js output/scripts/main.js
